name: python building

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pybuildjob1:
    runs-on: ubuntu-latest
    steps:
      - name: pybuildstep1
        uses: actions/checkout@v4
      - name: pybuildstep2
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: cat requirements.txt
      - run: pip install -r requirements.txt
      - run: ls -ltra
      - name: executing test
        run: pytest
        continue-on-error: true
      - name: checking error
        run: echo testing after error execution
      
      - name: build docker istallation and env setup 
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: build docker image
        run: |
          set -x

          docker version
          docker build -t satheeshmdu/mypydoc2 .

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker push
        run: docker push satheeshmdu/mypydoc2
